### PR TITLE
Be more similar to Test.@test interface

### PR DESCRIPTION
**Pull request by dralletje**
Specifically, and most hard to work around, getting local variables to work:

```julia
let
  i = 10
  @test i == 10
end
```

It does, but I'd like to have errors and testsets too (or rather just have the notebook a bit cleaned up)

### CODE REVIEW

**Comment by fonsp** [comment]
Yayyyy
I don't get your example though, is that inside a let block? Does that not work already?

**Comment by dralletje** [comment]
image

With a begin block it just happens to work because the variables is created in the same module.
Anything local doesn't work D:

image
image

But now........

image

**Comment by fonsp** [comment]
jeee xoxo

**Comment by fonsp** [comment]
@dralletje Can you merge this PR and maybe continue the work in a second PR? With this big PR open I can't work on the package anymore

**Pull request closed without merging**
